{{- if .Values.pingExporter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "CGW.fullname" . }}-ping-exporter
  labels:
    app: {{ template "CGW.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ping-exporter.yaml: |
{{ toYaml .Values.pingExporter.config | indent 4 }}
    version: "1.0"
{{- if .Values.pingExporter.targets }}
    ping:
      configurations:
{{ toYaml .Values.pingExporter.targets | indent 8 }}
{{- end }}
{{- end }}
