{{- if and .Values.ipsec.enabled .Values.ipsec.certs.privateKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "CGW.fullname" . }}-strongswan-privatekeys
  labels:
    app: {{ template "CGW.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.ipsec.certs.privateKeys | indent 2 }}
{{- end -}}
