{{- if and (.Values.ipsec.enabled) (.Values.ipsec.manualConfig) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "CGW.fullname" . }}-strongswan-secrets
  labels:
    app: {{ template "CGW.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.ipsec.strongswan.ipsecSecrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end -}}
